
SELECT DISTINCT
       RAT.TRX_NUMBER,
       RAT.PAYING_CUSTOMER_ID,
       RAS.NAME AS TRANSACTION_SOURCE,
       RAT.CUSTOMER_TRX_ID,
       TO_CHAR(RAT.TRX_DATE, 'DD-MM-YYYY') AS TRX_DATE,

       LINE.DESCRIPTION AS LINE_DESCRIPTION,
       LINE.ATTRIBUTE_CATEGORY,
       LINE.ATTRIBUTE1  AS BILL_ID,
       LINE.ATTRIBUTE2  AS LINE_NO,
       LINE.ATTRIBUTE3  AS CONTRACT_ID,
       LINE.ATTRIBUTE4  AS INVOICE_TYPE,
       LINE.ATTRIBUTE5  AS BUY_TRIP_NO_WB,
       LINE.ATTRIBUTE6  AS TRIP_START_DATE,
       LINE.ATTRIBUTE7  AS TRIP_END_DATE,
       LINE.ATTRIBUTE9  AS SELL_TRIP_NO,
       LINE.ATTRIBUTE10 AS INVOICE_PRINT_DESCRIPTION,

       LINE.LINE_TYPE,
       LINE.EXTENDED_AMOUNT AS LINE_AMOUNT,

       HZX.ACCOUNT_NUMBER,
       HSP.PARTY_NAME AS BILL_TO_CUSTOMER_NAME,

       TAX.EXTENDED_AMOUNT AS TAX_AMOUNT

FROM RA_CUSTOMER_TRX_ALL RAT,
     RA_BATCH_SOURCES_ALL RAS,
     RA_CUSTOMER_TRX_LINES_ALL LINE,
     RA_CUSTOMER_TRX_LINES_ALL TAX,
     HZ_CUST_ACCOUNTS HZX,
     HZ_PARTIES HSP

WHERE RAT.BATCH_SOURCE_SEQ_ID = RAS.BATCH_SOURCE_SEQ_ID
  AND RAT.CUSTOMER_TRX_ID     = LINE.CUSTOMER_TRX_ID
  AND LINE.LINE_TYPE          = 'LINE'

  AND TAX.LINK_TO_CUST_TRX_LINE_ID(+) = LINE.CUSTOMER_TRX_LINE_ID
  AND TAX.LINE_TYPE(+)                = 'TAX'

  AND RAT.BILL_TO_CUSTOMER_ID = HZX.CUST_ACCOUNT_ID
  AND HZX.PARTY_ID            = HSP.PARTY_ID

  AND RAT.TRX_NUMBER = NVL(:P_TRX_NUMBER, RAT.TRX_NUMBER)

ORDER BY RAT.TRX_NUMBER