SELECT
    PAPF.PERSON_NUMBER AS "Partner Employee ID",
    PPNF.DISPLAY_NAME AS "Partner Name",
    PC.CITIZENSHIP_ID,
    PC.LEGISLATION_CODE,
    PER_EXTRACT_UTILITY.GET_TERRITORY_NAME(PC.LEGISLATION_CODE) AS "Citizenship",
    TO_CHAR(PC.DATE_FROM,'MM/DD/YYYY') AS "Date From",
    TO_CHAR(PC.DATE_TO,'MM/DD/YYYY') AS "Date To",
    PC.CITIZENSHIP_STATUS AS "Citizenship Status",
    PEA.EMAIL_ADDRESS AS "Partner Work Email",
    (SELECT DISTINCT D.NAME
       FROM PER_DEPARTMENTS D
      WHERE D.ORGANIZATION_ID = PAAM.ORGANIZATION_ID
        AND D.EFFECTIVE_START_DATE =
            (SELECT MAX(D1.EFFECTIVE_START_DATE)
               FROM PER_DEPARTMENTS D1
              WHERE D1.ORGANIZATION_ID = D.ORGANIZATION_ID)
    ) AS "Department",
    (SELECT DISTINCT J.NAME
       FROM PER_JOBS_F_VL J
      WHERE J.JOB_ID = PAAM.JOB_ID
        AND J.EFFECTIVE_START_DATE =
            (SELECT MAX(J1.EFFECTIVE_START_DATE)
               FROM PER_JOBS_F_VL J1
              WHERE J1.JOB_ID = J.JOB_ID)
    ) AS "Job",
    (SELECT G.NAME
       FROM PER_GRADES G
      WHERE G.GRADE_ID = PAAM.GRADE_ID
        AND ROWNUM = 1
    ) AS "Grade"
FROM PER_CITIZENSHIPS PC,
     PER_ALL_PEOPLE_F PAPF,
     PER_ALL_ASSIGNMENTS_M PAAM,
     PER_PERSON_NAMES_F PPNF,
     PER_EMAIL_ADDRESSES PEA
WHERE PC.PERSON_ID (+) = PAPF.PERSON_ID
  AND PAPF.PERSON_ID = PAAM.PERSON_ID
  AND PAPF.PERSON_ID = PPNF.PERSON_ID
  AND PAPF.PERSON_ID = PEA.PERSON_ID
  AND PPNF.NAME_TYPE = 'GLOBAL'
  AND PEA.EMAIL_TYPE = 'W1'
  AND PAAM.ASSIGNMENT_TYPE = 'E'
  AND PAAM.PRIMARY_FLAG = 'Y'
  AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
  AND PAAM.ASSIGNMENT_STATUS_TYPE = 'ACTIVE'
  AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
  AND TRUNC(SYSDATE) BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
  AND TRUNC(SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE